apiVersion: apps/v1
kind: Deployment
metadata: 
  name: golang-app
  labels:
    app: golang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang-container
        image: pilotkode/simple-golang:latest
        ports:
        - containerPort: 3000
        envFrom: 
        - configMapRef: 
            name: db-config
---
apiVersion: v1 
kind: Service 
metadata: 
  name: golang-service
spec:
  type: LoadBalancer 
  selector: 
    app: golang
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000

